# 1 .Perceptron for Binary Classification
Implement the Perceptron algorithm for binary classification. 

a Generate a linearly separable dataset with 5 features, 2 classes, and 1000 samples
using sklearn’s make classification.

b Train your Perceptron model on this dataset and experiment with different
learning rates (e.g., 0.01, 0.1) and iterations (e.g., 50, 100).

c Plot the decision boundary for the best model on training data and evaluate the
model on test data

In [342]:
from sklearn.datasets import make_classification
X, y = make_classification(n_samples=1000,n_features=5,n_classes=2)
X.shape
y.shape
print(X)
print(y)


[[ 1.49333406e+00 -1.46289253e-01 -7.05686639e-01  1.03480227e+00
   7.34481336e-01]
 [ 1.34176696e+00 -1.04035648e+00  2.48169428e-01  1.55792015e+00
   1.05821747e+00]
 [-1.69506733e+00 -1.45918982e+00  2.43772449e+00 -9.26311608e-03
  -9.48115948e-02]
 ...
 [ 7.83702129e-01  8.43658104e-01  7.51189195e-01  1.34159256e+00
   8.91771551e-01]
 [-9.40996944e-01  8.75557658e-01 -8.51776324e-02 -1.02931509e+00
  -7.02021639e-01]
 [-1.23970474e+00  2.25387139e-03  2.17826903e+00  2.74758989e-01
   1.09168111e-01]]
[0 0 1 0 0 0 0 1 0 1 0 1 0 1 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 1 0 0 1 1 0 0 0
 1 0 0 1 1 1 0 1 1 1 1 1 0 0 0 0 0 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 0 0
 1 1 1 1 1 0 0 1 0 1 0 1 0 1 0 1 1 1 1 1 1 0 0 0 1 1 1 0 0 0 0 0 1 1 1 0 0
 0 1 0 0 1 1 1 0 0 0 1 1 0 1 0 1 1 1 1 0 0 1 1 1 0 1 1 0 1 1 0 0 1 1 0 1 1
 1 1 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 1 0 0 1 1 0 0 1 1 0 1
 0 1 1 0 1 1 1 1 1 1 0 1 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 1 1 1 1 0 0 0 0 1 0
 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 0

In [343]:
import numpy as  np
from numpy import random
class Perceptron:
    def __init__(self,input_size):
        self.weights= random.rand(1,input_size)
        # self.bias=random.randint(input_size)
        self.bias=1
        print(self.weights)
    def sigmoid(self,z):
        if z<0:
            return 0
        else:
            return 1
        # return (1/1+np.exp(-z))
    def predict(self,value):
        z=np.dot(value,self.weights[0].T)+self.bias
        return self.sigmoid(z)
    def train(self,X,Y,lr,epoche):
        
        for _ in range(epoche):
            # for i in range(len(X)):
            i=random.randint(len(X))
            current_input=X[i]
            current_input=current_input.reshape(1,5)
            target=Y[i]
            prediction=self.predict(current_input)
            error=target-prediction
            weights_update=lr*error
            
            self.weights+=weights_update
            self.bias+=weights_update
            # weights_update=error*prediction*(1-prediction)*current_input
            # self.weights=weights_update*lr
        
    
            # bias_update=error*prediction*(1-prediction)
            # self.bias=bias_update*lr
        
    def evaluates(self,X,y):
        count=0
        
        for i in range(len(X)):
            prediction=self.predict(X[i])
            if prediction==0:
                c=1

            else:
                c=0
            if y[i]==c:
                count+=1
        value=count/len(X)
        print("the accuracy is "+str(value))
            
    def pri(self):
        print("ks")
        print(self.weights[0])
        



In [344]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(

    X, y, test_size=0.33, random_state=42)

In [377]:
a=Perceptron(5)
a.train(X_train,y_train,0.05,50)
a.evaluates(X_test,y_test)


[[0.40081662 0.64061067 0.11028672 0.71926122 0.84159051]]
the accuracy is 0.7333333333333333


In [381]:
a=Perceptron(5)
a.train(X_train,y_train,0.1,100)
a.evaluates(X_test,y_test)




[[0.72465693 0.58758045 0.18727741 0.83505693 0.96790516]]
the accuracy is 0.806060606060606


In [ ]:
#plot 



# 3.Logistic Regression
Modify your algorithm to predict probabilities instead of discrete outputs.

a Train the modified model on the same 'MNIST' dataset.

b Evaluate the model on the same test set and report the accuracy and classifica-
tion metrics

In [382]:
import numpy as  np
from numpy import random
class Perceptron_sigmoid:
    def __init__(self,input_size):
        self.weights= random.rand(1,input_size)
        # self.bias=random.randint(input_size)
        self.bias=1
        print(self.weights)
    def sigmoid(self,z):
      
        return (1/1+np.exp(-z))
    def predict(self,value):
        z=np.dot(value,self.weights[0].T)+self.bias
        return self.sigmoid(z)
    def train(self,X,Y,lr,epoche):
        
        for _ in range(epoche):
            # for i in range(len(X)):
            i=random.randint(len(X))
            current_input=X[i]
            current_input=current_input.reshape(1,5)
            target=Y[i]
            prediction=self.predict(current_input)
            error=target-prediction
            weights_update=lr*error
            
            self.weights+=weights_update
            self.bias+=weights_update
            # weights_update=error*prediction*(1-prediction)*current_input
            # self.weights=weights_update*lr
        
    
            # bias_update=error*prediction*(1-prediction)
            # self.bias=bias_update*lr
        
    def evaluates(self,X,y):
        count=0
        
        for i in range(len(X)):
            prediction=self.predict(X[i])
            if prediction<0.5:
                c=1

            else:
                c=0
            if y[i]==c:
                count+=1
        value=count/len(X)
        print("the accuracy is "+str(value))
    def pred(self,X,y):
        y_pred=[]
        y_true=[]
        for i in range(len(X)):
            
            # y_pred.append(self.predict(X[i]))
            if self.predict(X[i])<0.5:
                y_pred.append(0)
            else:
                y_pred.append(1)
            
            y_true.append(y[i])
        return y_true,y_pred
            
    def pri(self):
        print("ks")
        print(self.weights[0])
        



In [339]:
# # from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [383]:
a=Perceptron_sigmoid(5)
a.train(X_train,y_train,0.05,10)
a.evaluates(X_test,y_test)

a.pri()

[[0.42460707 0.57358613 0.26684    0.10157472 0.17042074]]
the accuracy is 0.49393939393939396
ks
[-0.07949524  0.06948383 -0.2372623  -0.40252759 -0.33368157]


In [384]:
from sklearn.metrics import classification_report
y_true,y_pred=a.pred(X_test,y_test)
target_names = ['class 0', 'class 1']
print(classification_report(y_true, y_pred, target_names=target_names))

              precision    recall  f1-score   support

     class 0       0.00      0.00      0.00       163
     class 1       0.51      1.00      0.67       167

    accuracy                           0.51       330
   macro avg       0.25      0.50      0.34       330
weighted avg       0.26      0.51      0.34       330



/home2/student/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home2/student/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home2/student/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
