In [3]:
import pandas as pd

In [4]:
df=pd.read_csv("/content/data.csv")
Text=df[["Text"]]
Label=df[["Label"]]


In [5]:
import nltk
from nltk.corpus import stopwords
import spacy
import string



# Create translation table

translator = str.maketrans('', '', string.punctuation)

# Remove punctuation


nltk.download('stopwords')
words=(stopwords.words('english'))
nlp = spacy.load("en_core_web_sm")
# print(words)
X=[]
x=df["Text"]
for text in x:
  text.lower()
  text= text.translate(translator)

  doc = nlp(text)


  # Remove stopwords
  filtered_words = [token.text for token in doc if not token.is_stop]

  # Join the filtered words to form a clean text
  text = ' '.join(filtered_words)
  X.append(text)




[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [6]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenize=Tokenizer()
tokenize.fit_on_texts(X)
sequences = tokenize.word_index



In [7]:
print(X[99])

   clayton cramer   subject     age consent     child molestation   article     hot young star   writes     clayton cramer   read carefully           article    roy radow   writes         assumed   nambla   agree specific      agendas participating group        assumed group      supports specific goals ideals     yeah   like shouldn t assume aryan nations supports genocide        fooling       clayton e   cramer   uunet pyramid   optilink cramer   opinions     relations people mutual consent    


In [8]:

y=df["Label"]
input=[]
for i in X:
  input.append(i.split())

In [9]:
print(input[0])


['phill', 'hallam', 'baker', 'subject', 'waco', 'survivors', 'april', 'article', 'rob', 'strom', 'writes', 'article', 'phill', 'hallam', 'baker', 'writes', 'order', 'reject', 'word', 'fbi', 'batf', 'neccessary', 'beleive', 'words', 'man', 'murdered', 'children', 'ordered', 'suicide', 'murder', 'followers', 'according', 'account', 'given', 'batf', 'attempted', 'serve', 'warrant', 'koresh', 'ranch', 'met', 'gunfire', 'deliberate', 'attempt', 'murder', 'koresh', 'gun', 'supporter', 'claim', 'batf', 'started', 'shooting', 'simply', 'stand', 'aft', 'gone', 'start', 'shooting', 'gone', 'heavier', 'grade', 'weaponry', 'standard', 'issue', 'handguns', 'practical', 'purposes', 'unarmed', 'b', 'd', 'followers', 'automatic', 'weapons', 'people', 'want', 'gun', 'control', 'obviously', 'discount', 'entire', 'government', 'story', 'simply', 'rationalisation', 'simply', 'dismiss', 'government', 'incompetent', 'require', 'come', 'solution', 'instead', 'come', 'government', 'conspiracy', 'theory', 'gov

In [10]:

for i in range(len(input)):

  for j in range(len(input[i])):
    word=input[i][j]
    input[i][j]=sequences[word]





In [11]:
import tensorflow.keras
input=keras.utils.pad_sequences(input, padding='post')

from sklearn import preprocessing
lab=preprocessing.LabelEncoder()
df["Label"]=lab.fit_transform(df["Label"])


In [12]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense,LSTM,Embedding
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from tensorflow import keras
from sklearn.model_selection import train_test_split
X=input
y=df["Label"]
print(X)

# using the train test split function
X_train, X_test, y_train, y_test = train_test_split(X,y ,
                                   random_state=104,
                                   test_size=0.25,
                                   shuffle=True)




rnn_model = Sequential()
rnn_model.add(Embedding(len(input[0]),100,input_length=len(input[0])))
rnn_model.add(SimpleRNN(50))
rnn_model.add(Dense(6, activation='sigmoid'))

rnn_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])


print(y)
rnn_model.fit(X_train, y_train, epochs=5)


[[ 1565  2132  1551 ...     0     0     0]
 [  775     2  8081 ...     0     0     0]
 [ 2544 21672     3 ...     0     0     0]
 ...
 [   45   235  2275 ...     0     0     0]
 [ 1108  1945     3 ...     0     0     0]
 [ 4053   192  3619 ...     0     0     0]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


0       3
1       3
2       3
3       3
4       3
       ..
5346    0
5347    0
5348    0
5349    0
5350    0
Name: Label, Length: 5351, dtype: int64
Epoch 1/5
126/126 ━━━━━━━━━━━━━━━━━━━━ 56s 424ms/step - accuracy: 0.1740 - loss: 1.7927
Epoch 2/5
126/126 ━━━━━━━━━━━━━━━━━━━━ 81s 424ms/step - accuracy: 0.1744 - loss: 1.7792
Epoch 3/5
126/126 ━━━━━━━━━━━━━━━━━━━━ 81s 419ms/step - accuracy: 0.1769 - loss: 1.7829
Epoch 4/5
126/126 ━━━━━━━━━━━━━━━━━━━━ 83s 429ms/step - accuracy: 0.1927 - loss: 1.7780
Epoch 5/5
126/126 ━━━━━━━━━━━━━━━━━━━━ 81s 418ms/step - accuracy: 0.1808 - loss: 1.8000


In [16]:
rnn_model.summary()


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ (None, 6490, 100)           │         649,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn (SimpleRNN)               │ (None, 50)                  │           7,550 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 6)                   │             306 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,970,570 (7.52 MB)

 Trainable params: 656,856 (2.51 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,313,714 (5.01 MB)

In [18]:



# define model
model_lstm = Sequential()
model_lstm.add(Embedding(len(input[0]),100,input_length=len(input[0])))
model_lstm.add(LSTM(64))
model_lstm.add(Dense(6))
model_lstm.compile(optimizer='adam', loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model_lstm.summary()
model_lstm.fit(X_train,y_train, epochs=5)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/5
126/126 ━━━━━━━━━━━━━━━━━━━━ 27s 172ms/step - accuracy: 0.1893 - loss: 2.6050
Epoch 2/5
126/126 ━━━━━━━━━━━━━━━━━━━━ 38s 172ms/step - accuracy: 0.1843 - loss: 1.7918
Epoch 3/5
126/126 ━━━━━━━━━━━━━━━━━━━━ 41s 171ms/step - accuracy: 0.2010 - loss: 1.7918
Epoch 4/5
126/126 ━━━━━━━━━━━━━━━━━━━━ 41s 172ms/step - accuracy: 0.1920 - loss: 1.7918
Epoch 5/5
126/126 ━━━━━━━━━━━━━━━━━━━━ 41s 170ms/step - accuracy: 0.1844 - loss: 1.7918


In [ ]:
from tensorflow.keras.layers import GRU
# define model
model_gru = Sequential()
model_gru.add(Embedding(len(input[0]),100,input_length=len(input[0])))
model_gru.add(GRU(100))
model_gru.add(Dense(6))
model_gru.compile(optimizer='adam', loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model_gru.summary()
model_gru.fit(X_train,y_train, epochs=5)

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ gru (GRU)                            │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/5
126/126 ━━━━━━━━━━━━━━━━━━━━ 26s 189ms/step - accuracy: 0.1867 - loss: 6.8208
Epoch 2/5
